---
name: Bug Report
description: "Report a bug or issue with the mod"
title: "[BUG] "
labels: bug
body:
  - type: input
    id: mod_version
    attributes:
      label: "Mod Version"
      description: "Provide the version of the mod you are using (e.g., 1.2.3)."

  - type: input
    id: minecraft_version
    attributes:
      label: "Minecraft Version"
      description: "Specify the Minecraft version (e.g., 1.20.1)."

  - type: dropdown
    id: mod_loader
    attributes:
      label: "Mod Loader"
      description: "Indicate the mod loader you are using."
      options:
        - "Forge"
        - "Fabric"
        - "Quilt"
        - "Other (specify in Additional Context)"

  - type: textarea
    id: bug_description
    attributes:
      label: "Describe the Bug"
      description: "A clear and concise description of the bug or issue."

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Provide steps to reproduce the behavior."
      placeholder: |
        1. Open the game.
        2. Perform '...'
        3. See error.

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen instead?"

  - type: textarea
    id: logs
    attributes:
      label: "Game Logs"
      description: "Include relevant logs (e.g., latest.log or debug.log)."
      placeholder: "Paste a link to logs from Pastebin (https://pastebin.com) or Gist (https://gist.github.com)."

  - type: textarea
    id: installed_mods
    attributes:
      label: "Installed Mods"
      description: "List all installed mods or upload your mods folder contents. If using a modpack, include its name and version."

  - type: textarea
    id: environment_details
    attributes:
      label: "Environment Details"
      description: "Provide information about your environment, such as:"
      placeholder: |
        - Operating System: [e.g., Windows 11, macOS Ventura, Ubuntu 22.04]
        - Java Version: [e.g., Java 17]

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other relevant context about the problem, such as changes to configuration files or world settings."
